version: '3.8'

services:
  secrets-agent:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
      - DATABASE_URL=file:./data/secrets-agent.db
      - JWT_SECRET=${JWT_SECRET:-change-this-in-production}
    volumes:
      - secrets_data:/app/data
      - secrets_logs:/app/logs
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3000/api/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    networks:
      - secrets_network

  # Optional: Add a reverse proxy for production
  nginx:
    image: nginx:alpine
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
      - ./ssl:/etc/nginx/ssl:ro
    depends_on:
      - secrets-agent
    restart: unless-stopped
    networks:
      - secrets_network

volumes:
  secrets_data:
    driver: local
  secrets_logs:
    driver: local

networks:
  secrets_network:
    driver: bridge 