# MCP Governance Configuration

version: "1.0"

# Level 1: System-wide Governance
system:
  roles:
    admin:
      description: "System-wide administrator"
      permissions: ["manage_agents", "manage_tools", "manage_rules", "manage_secrets"]
    auditor:
      description: "System-wide auditor"
      permissions: ["view_logs", "view_metrics", "view_audit_trail"]
  
  policies:
    security:
      - "All agents must be authenticated"
      - "All tool access must be authorized"
      - "All secrets must be encrypted"
    compliance:
      - "All actions must be logged"
      - "All metrics must be collected"
      - "All audit trails must be maintained"

# Level 2: Project Governance
project:
  roles:
    project_admin:
      description: "Project administrator"
      permissions: ["manage_project_agents", "manage_project_tools", "manage_project_rules"]
    project_user:
      description: "Project user"
      permissions: ["use_project_tools", "view_project_logs"]
  
  policies:
    tool_management:
      - "Tools must be explicitly enabled per project"
      - "Tool configurations must be version controlled"
      - "Tool access must be logged"
    agent_management:
      - "Agents must be assigned to specific projects"
      - "Agent permissions must be scoped to project"
      - "Agent actions must be audited"

# Level 3: Agent Governance
agent:
  types:
    system_agent:
      description: "System-level automation agent"
      capabilities: ["manage_infrastructure", "manage_security", "manage_compliance"]
    project_agent:
      description: "Project-specific automation agent"
      capabilities: ["execute_tools", "access_resources", "manage_workflows"]
    user_agent:
      description: "User-specific assistant agent"
      capabilities: ["assist_user", "execute_commands", "manage_tasks"]
  
  policies:
    execution:
      - "Agents must follow least privilege principle"
      - "Agent actions must be traceable"
      - "Agent resources must be isolated"
    interaction:
      - "Agents must respect user preferences"
      - "Agents must maintain context"
      - "Agents must handle errors gracefully"

# MCP Management
mcp:
  registration:
    required_metadata:
      - "tool_name"
      - "version"
      - "description"
      - "security_requirements"
      - "resource_requirements"
    validation_rules:
      - "All metadata must be provided"
      - "Version must be semantic"
      - "Security requirements must be explicit"
  
  lifecycle:
    states:
      - "registered"
      - "validated"
      - "approved"
      - "active"
      - "suspended"
      - "deprecated"
    transitions:
      - from: "registered"
        to: "validated"
        requires: ["security_review", "compliance_check"]
      - from: "validated"
        to: "approved"
        requires: ["admin_approval", "risk_assessment"]

# Rule Management
rules:
  categories:
    security_rules:
      description: "Security and access control rules"
      priority: 1
    compliance_rules:
      description: "Compliance and audit rules"
      priority: 2
    operational_rules:
      description: "Operational and performance rules"
      priority: 3
  
  enforcement:
    levels:
      - "strict"
      - "warning"
      - "advisory"
    actions:
      - "block"
      - "alert"
      - "log"

# Vault Integration
vault:
  secret_types:
    - "api_keys"
    - "certificates"
    - "credentials"
    - "tokens"
  
  access_patterns:
    - pattern: "project/{project_id}/secrets/{secret_type}"
      description: "Project-specific secrets"
    - pattern: "system/secrets/{secret_type}"
      description: "System-wide secrets"
  
  rotation_policies:
    api_keys: "90_days"
    certificates: "1_year"
    credentials: "30_days"
    tokens: "7_days" 