name: Docker Compose CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
        
      - name: Build and start services
        run: docker-compose up -d
        
      - name: Wait for services to start
        run: sleep 10
        
      - name: Check API health
        run: |
          curl -f http://localhost:5001/api/health || (docker-compose logs && exit 1)
        
      - name: Run API tests
        run: |
          docker-compose exec -T api python test_api.py
        
      - name: Dump logs on failure
        if: failure()
        run: docker-compose logs
        
      - name: Stop containers
        if: always()
        run: docker-compose down 