name: 'Secrets Rotation'

on:
  schedule:
    - cron: '0 0 * * 0'

jobs:
  rotate:
    name: Rotate secrets
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'
      - name: Install dependencies
        run: npm ci
      - name: Rotate secrets via script
        env:
          VAULT_ADDR: ${{ secrets.VAULT_ADDR }}
          VAULT_TOKEN: ${{ secrets.VAULT_TOKEN }}
        run: npx ts-node scripts/rotate-secrets.ts
      - name: Commit rotated secrets
        run: |
          git config user.name 'github-actions[bot]'
          git config user.email 'github-actions[bot]@users.noreply.github.com'
          git add .env.template secrets.template.yaml
          git diff --quiet && git commit -m 'chore: rotate secrets via rotation script' || echo 'No changes to commit'
      - name: Push changes
        uses: ad-m/github-push-action@v0.6.0
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}