name: 'Secrets Preflight'

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  preflight:
    name: Preflight secrets scan
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'
      - name: Install dependencies
        run: npm ci
      - name: Install sops and age
        run: |
          sudo apt-get update && sudo apt-get install -y gnupg2 age
          curl -sSL https://github.com/mozilla/sops/releases/download/v3.8.2/sops-v3.8.2.linux.amd64 -o sops
          chmod +x sops && sudo mv sops /usr/local/bin/
      - name: Run preflight
        run: npx ts-node apps/api/agents/secrets/preflight.ts
      - name: Commit changes
        run: |
          git config user.name 'github-actions[bot]'
          git config user.email 'github-actions[bot]@users.noreply.github.com'
          git add .env.template secrets.template.yaml
          git diff --quiet && git commit -m 'chore: update secrets templates via preflight' || echo 'No changes to commit'
      - name: Push changes
        uses: ad-m/github-push-action@v0.6.0
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}