name: VS Code Extension

on:
  push:
    branches: [ main ]
    tags:
      - 'v*'
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3
        
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '16'
          
      - name: Install dependencies
        run: |
          cd extension_api/vscode
          npm install
          npm install -g @vscode/vsce
          
      - name: Package VS Code extension
        run: |
          cd extension_api/vscode
          vsce package
          
      - name: Upload extension package
        uses: actions/upload-artifact@v3
        with:
          name: secrets-agent-extension
          path: extension_api/vscode/*.vsix
  
  publish:
    needs: build
    if: startsWith(github.ref, 'refs/tags/v')
    runs-on: ubuntu-latest
    
    steps:
      - name: Download artifact
        uses: actions/download-artifact@v3
        with:
          name: secrets-agent-extension
          
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '16'
          
      - name: Install vsce
        run: npm install -g @vscode/vsce
        
      - name: Publish to VS Code Marketplace
        if: success()
        run: vsce publish -p ${{ secrets.VSCODE_MARKETPLACE_TOKEN }}
        
      - name: Create GitHub Release
        uses: softprops/action-gh-release@v1
        with:
          files: "*.vsix"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} 